In [13]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
bechdel_df = pd.read_csv('my_data/updated_bechdel_3.csv')
bechdel_df.head()

,year,title,score,passing,imdb_id,director_fnbt,writer_fnbt,exec_fnbt,producer_fnbt,overall_fnbt,new_budgets,new_revenues
0,2019.0,Alita: Battle Angel,3.0,1.0,tt0437086,0.0,1.0,0.0,0.0,1.0,170000000.0,359700000.0
1,2019.0,Close,3.0,1.0,tt5316540,1.0,1.0,0.0,0.0,2.0,0.0,0.0
2,2019.0,Cold Pursuit,1.0,0.0,tt5719748,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2019.0,The Kid Who Would Be King,1.0,0.0,tt6811018,0.0,0.0,0.0,1.0,1.0,0.0,0.0
4,2019.0,Polar,2.0,0.0,tt4139588,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
bechdel_df.rename(index=str, columns={'director_fnbt': 'director_gender', 'writer_fnbt': 'writer_gender',
                                     'exec_fnbt': 'exec_gender', 'producer_fnbt': 'producer_gender',
                                     'overall_fnbt': 'overall_gender', 'new_budgets': 'budget',
                                     'new_revenues': 'revenue'}, inplace=True)

In [7]:
bechdel_df.to_csv('my_data/updated_bechdel_4.csv', index=False)

In [8]:
bechdel_with_budget_and_revenue = bechdel_df.loc[(bechdel_df.budget != 0) & (bechdel_df.revenue != 0)]
bechdel_with_budget_and_revenue.head()

,year,title,score,passing,imdb_id,director_gender,writer_gender,exec_gender,producer_gender,overall_gender,budget,revenue
0,2019.0,Alita: Battle Angel,3.0,1.0,tt0437086,0.0,1.0,0.0,0.0,1.0,170000000.0,359700000.0
8,2018.0,A Quiet Place,1.0,0.0,tt6644200,0.0,0.0,0.0,0.0,0.0,17000000.0,259168321.0
9,2018.0,A Quiet Place,1.0,0.0,tt6644200,0.0,0.0,0.0,0.0,0.0,17000000.0,340939361.0
10,2018.0,A Simple Favor,3.0,1.0,tt7040874,0.0,1.0,0.0,1.0,2.0,20000000.0,42600000.0
11,2018.0,A Star Is Born,3.0,1.0,tt1517451,0.0,1.0,0.0,0.0,1.0,36000000.0,403588149.0

In [9]:
bechdel_with_budget_and_revenue.shape

(3498, 12)

#### New dataset with no zero values to practice using with Dash

In [11]:
bechdel_with_budget_and_revenue.to_csv('my_data/practice_data/bechdel_no_zeros.csv', index=False)

In [12]:
bechdel_with_budget_and_revenue

,year,title,score,passing,imdb_id,director_gender,writer_gender,exec_gender,producer_gender,overall_gender,budget,revenue
0,2019.0,Alita: Battle Angel,3.0,1.0,tt0437086,0.0,1.0,0.0,0.0,1.0,170000000.0,3.597000e+08
8,2018.0,A Quiet Place,1.0,0.0,tt6644200,0.0,0.0,0.0,0.0,0.0,17000000.0,2.591683e+08
9,2018.0,A Quiet Place,1.0,0.0,tt6644200,0.0,0.0,0.0,0.0,0.0,17000000.0,3.409394e+08
10,2018.0,A Simple Favor,3.0,1.0,tt7040874,0.0,1.0,0.0,1.0,2.0,20000000.0,4.260000e+07
11,2018.0,A Star Is Born,3.0,1.0,tt1517451,0.0,1.0,0.0,0.0,1.0,36000000.0,4.035881e+08
12,2018.0,A Wrinkle in Time,3.0,1.0,tt1620680,1.0,1.0,1.0,1.0,4.0,100000000.0,1.326759e+08
14,2018.0,Alpha,0.0,0.0,tt4244998,0.0,0.0,0.0,0.0,0.0,51000000.0,3.580844e+07
15,2018.0,American Animals,1.0,0.0,tt6212478,0.0,0.0,0.0,0.0,0.0,3000000.0,2.847319e+06
17,2018.0,Annihilation,3.0,1.0,tt2798920,0.0,0.0,0.0,0.0,0.0,40000000.0,4.307092e+07
18,2018.0,Ant-Man and the Wasp,3.0,1.0,tt5095030,0.0,0.0,1.0,0.0,1.0,140000000.0,6.226741e+08
20,2018.0,Aquaman,3.0,1.0,tt1477834,0.0,0.0,1.0,0.0,1.0,200000000.0,1.138891e+09
21,2018.0,Avengers: Infinity War,3.0,1.0,tt4154756,0.0,0.0,1.0,0.0,1.0,400000000.0,6.788155e+08
25,2018.0,Black Panther,3.0,1.0,tt1825683,0.0,0.0,0.0,0.0,0.0,200000000.0,1.346913e+09
26,2018.0,BlacKkKlansman,3.0,1.0,tt7349662,0.0,0.0,0.0,0.0,0.0,15000000.0,4.868660e+07
28,2018.0,Blockers,3.0,1.0,tt2531344,1.0,0.0,0.0,0.0,1.0,21000000.0,9.367479e+07
29,2018.0,Bohemian Rhapsody,2.0,0.0,tt1727824,0.0,0.0,0.0,0.0,0.0,52000000.0,8.702000e+08
30,2018.0,Book Club,3.0,1.0,tt6857166,0.0,0.0,0.0,0.0,0.0,10000000.0,7.872029e+07
31,2018.0,Bumblebee,1.0,0.0,tt4701182,0.0,1.0,0.0,0.0,1.0,135000000.0,4.595000e+08
36,2018.0,Crazy Rich Asians,3.0,1.0,tt3104988,0.0,1.0,0.0,1.0,2.0,30000000.0,2.385000e+08
37,2018.0,Creed II,3.0,1.0,tt6343314,0.0,0.0,0.0,0.0,0.0,50000000.0,2.134000e+08
38,2018.0,Deadpool 2,2.0,0.0,tt5463162,0.0,0.0,0.0,1.0,1.0,110000000.0,7.850469e+08
43,2018.0,Fantastic Beasts: The Crimes of Grindelwald,2.0,0.0,tt4123430,0.0,1.0,0.0,0.0,1.0,200000000.0,6.534000e+08
44,2018.0,The Favourite,3.0,1.0,tt5083738,0.0,1.0,0.0,0.0,1.0,15000000.0,8.212480e+07
45,2018.0,First Man,3.0,1.0,tt1213641,0.0,0.0,0.0,0.0,0.0,70000000.0,1.005462e+08
47,2018.0,The First Purge,1.0,0.0,tt6133466,0.0,0.0,0.0,0.0,0.0,13000000.0,4.195394e+07
49,2018.0,Game Night,3.0,1.0,tt2704998,0.0,0.0,0.0,0.0,0.0,37000000.0,8.550000e+07
50,2018.0,The Girl in the Spider's Web,3.0,1.0,tt5177088,0.0,0.0,0.0,1.0,1.0,43000000.0,1.789434e+07
51,2018.0,Green Book,1.0,0.0,tt6966692,0.0,0.0,0.0,0.0,0.0,23000000.0,6.300540e+07
53,2018.0,Halloween,3.0,1.0,tt1502407,0.0,0.0,0.0,0.0,0.0,10000000.0,2.537000e+08
54,2018.0,The Hate U Give,3.0,1.0,tt5580266,0.0,1.0,0.0,0.0,1.0,23000000.0,2.916354e+07
...,...,...,...,...,...,...,...,...,...,...,...,...
7325,1934.0,It Happened One Night,3.0,1.0,tt0025316,0.0,0.0,0.0,0.0,0.0,325000.0,4.500000e+06
7329,1934.0,The Man Who Knew Too Much,3.0,1.0,tt0025452,0.0,0.0,0.0,0.0,0.0,2500000.0,1.025000e+07
7332,1934.0,The Painted Veil,1.0,0.0,tt0025617,0.0,1.0,0.0,0.0,1.0,947000.0,1.120000e+06
7336,1933.0,42nd Street,3.0,1.0,tt0024034,0.0,0.0,0.0,0.0,0.0,439000.0,2.281000e+06
7339,1933.0,Cavalcade,3.0,1.0,tt0023876,0.0,0.0,0.0,0.0,0.0,1180280.0,7.630000e+06
7345,1933.0,Gold Diggers of 1933,3.0,1.0,tt0024069,0.0,0.0,0.0,0.0,0.0,433000.0,3.200000e+06
7347,1933.0,King Kong,0.0,0.0,tt0024216,0.0,1.0,0.0,0.0,1.0,672000.0,1.000000e+07
7350,1933.0,Queen Christina,3.0,1.0,tt0024481,0.0,1.0,0.0,0.0,1.0,1114000.0,2.610000e+06
7359,1932.0,Grand Hotel,3.0,1.0,tt0022958,0.0,1.0,0.0,0.0,1.0,700000.0,2.594000e+06
7375,1932.0,White Zombie,0.0,0.0,tt0023694,0.0,0.0,0.0,0.0,0.0,50000.0,8.000000e+06
7379,1931.0,City Lights,3.0,1.0,tt0021749,0.0,0.0,0.0,0.0,0.0,1500000.0,5.000000e+06
7380,1931.0,Dracula,2.0,0.0,tt0021814,0.0,0.0,0.0,0.0,0.0,355000.0,1.012189e+06
7381,1931.0,Frankenstein,1.0,0.0,tt0021884,0.0,0.0,0.0,0.0,0.0,291000.0,1.200000e+07
7388,1931.0,Mata Hari,3.0,1.0,tt0023196,0.0,0.0,0.0,0.0,0.0,558000.0,2.227000e+06
7409,1929.0,Broadway Melody,3.0,1.0,tt0019729,0.0,0.0,0.0,0.0,0.0,379000.0,4.358000e+06
7434,1927.0,The Jazz Singer,1.0,0.0,tt0018037,0.0,0.0,0.0,0.0,0.0,422000.0,3.000000e+06
7436,1927.0,Metropolis,1.0,0.0,tt0017136,0.0,1.0,0.0,0.0,1.0,92620000.0,6.504220e+05
7437,1927.0,My Best Girl,3.0,1.0,tt0018183,0.0,0.0,0.0,1.0,1.0,483103.0,1.027757e+06
7443,1926.0,Flesh and the Devil,1.0,0.0,tt0016884,0.0,0.0,0.0,0.0,0.0,373000.0,6.580000e+05
7449,1925.0,The Big Parade,2.0,0.0,tt0015624,0.0,0.0,0.0,0.0,0.0,245000.0,2.200000e+07
7452,1925.0,The Gold Rush,0.0,0.0,tt0015864,0.0,0.0,0.0,0.0,0.0,923000.0,2.500000e+06
7473,1922.0,Foolish Wives,3.0,1.0,tt0013140,0.0,0.0,0.0,0.0,0.0,1100000.0,4.002000e+05
7483,1921.0,The Kid,0.0,0.0,tt0012349,0.0,0.0,0.0,0.0,0.0,250000.0,2.500000e+06
7500,1916.0,Intolerance: Love's Struggle Throughout the Ages,0.0,0.0,tt0006864,0.0,1.0,0.0,0.0,1.0,2000000.0,8.394751e+06
7504,1915.0,The Birth of a Nation,2.0,0.0,tt0004972,0.0,0.0,0.0,0.0,0.0,110000.0,1.100000e+07
7570,1959.0,Sleeping Beauty,3.0,1.0,tt0053285,0.0,0.0,0.0,0.0,0.0,6000000.0,5.160000e+07
7588,2008.0,The Tale of Despereaux,3.0,1.0,tt0420238,0.0,0.0,0.0,1.0,1.0,60000000.0,8.690000e+07
7589,2007.0,Rush Hour 3,1.0,0.0,tt00293564,0.0,0.0,0.0,0.0,0.0,140000000.0,2.580000e+08
7592,1999.0,Pokemon: The Movie 2000,3.0,1.0,tt0210234,0.0,0.0,0.0,1.0,1.0,30000000.0,1.339000e+08
7609,2013.0,The Immigrant,3.0,1.0,tt1951181,0.0,0.0,0.0,0.0,0.0,16000000.0,5.900000e+06

In [14]:
# simple comparison of number of movies that pass vs movies that do not pass